name: myapp

services:
   mydbapp:
      build: ./web
      image: myweb:latest
      ports:
        - "8888:8080"
      depends_on:
        - db

   db:
      build: ./db
      image: mydb:latest
      environment:
        POSTGRES_PASSWORD: postgres
        POSTGRES_USER: postgres
        POSTGRES_DB: postgres
        POSTGRES_HOST: db
      volumes:
        - db_data:/var/lib/postgresql/data
        - ./db:/docker-entrypoint-initdb.d
      container_name: db

volumes:
   db_data:
